[[main]]
name = "Inicio"
url = "/"
weight = 1

[[main]]
name = "Productos"
identifier = "products"
url = "/products/"
weight = 2

[[main]]
name = "Nosotros"
url = "/#about"
weight = 3

[[main]]
name = "Contacto"
url = "/#contact"
weight = 4

[[footer_left]]
name = "Productos"
url = "/products/"

[[footer_left]]
name = "Nosotros"
url = "/#about"

[[footer_left]]
name = "Contacto"
url = "/#contact"

[[footer_middle]]
name = "Política de privacidad"
url = "/privacy-policy"

[[footer_middle]]
name = "Términos y condiciones"
url = "/terms-conditions"

[[footer_right]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/alan-zhou-42b224415"

[[footer_right]]
name = "Correo electrónico"
url = "mailto:sales@int-rock.com"
