baseURL = "https://alanzhou910103-ship-it.github.io/azk.website/"
title = "AZK"
theme = "azk"
timeZone = "Asia/Shanghai"
hasCJKLanguage = true

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
