baseURL = "https://int-rock.com/"
title = "int-rock"
theme = "azk"
timeZone = "Asia/Shanghai"
hasCJKLanguage = true

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
